# Generated by Django 4.1.3 on 2022-11-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('no_identidad', models.IntegerField()),
            ],
        ),
    ]
